"""Exercise the actual Shiny UI, downloads and persistence with Playwright.
Requires Python Playwright and Chromium; run the local app first.
Usage: python3 tests/browser_flow.py --archive /tmp/sportgen-flexible-fixture.json
"""
import argparse
import csv
import json
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

parser = argparse.ArgumentParser()
parser.add_argument('--url', default='http://127.0.0.1:3839')
parser.add_argument('--archive', required=True)
parser.add_argument('--out', default='.impeccable/review')
args = parser.parse_args()
out = Path(args.out).resolve(); out.mkdir(parents=True, exist_ok=True)
checks = []

def check(name, value):
    assert value, name
    checks.append(name)
    print('PASS', name, flush=True)

with sync_playwright() as p:
    browser = p.chromium.launch()
    context = browser.new_context(viewport={'width':1440, 'height':1000}, accept_downloads=True)
    page = context.new_page(); page.set_default_timeout(25000)
    errors = []; page.on('pageerror', lambda e: errors.append(str(e)))
    def shot(name):
        page.screenshot(path=str(out / (name + '.png')), full_page=True)
    def click(locator, name):
        shot(name+'-before'); locator.click(); page.wait_for_timeout(250); shot(name+'-after')
    def tab(name):
        page.get_by_role('tab',name=name,exact=True).click()
    def selected():
        return page.locator('[data-selected]').evaluate_all('(els)=>els.map(el=>el.dataset.selected)')
    def download(button, name):
        with page.expect_download() as pending: button.click()
        path = out/name; pending.value.save_as(str(path)); return path
    def rows_csv(path):
        with path.open(encoding='utf-8-sig',newline='') as f:
            reader=csv.DictReader(f); return reader.fieldnames,list(reader)
    page.goto(args.url, wait_until='domcontentloaded')
    tab('Настроить таблицу'); expect(page.locator('#selected-column-list .selected-row')).to_have_count(13)
    if page.locator('#search-panel').get_attribute('open') is not None:
        click(page.locator('#search-panel > summary'),'search-collapse')
    click(page.locator('[data-preset="rna"]'),'rna-preset')
    check('RNA preset exposes new fields', all(x in selected() for x in ['mirna','cell_line','disease']))
    click(page.locator('#clear-columns'),'clear-columns')
    check('Empty draft cannot be applied',page.locator('#apply-columns').is_disabled())
    for field in ['title','disease','cell_line','mirna']:
        page.locator('[data-column="'+field+'"]').check()
    click(page.get_by_role('button',name='Выше: МикроРНК (miRNA)',exact=True),'move-rna')
    page.get_by_role('button',name='Выше: МикроРНК (miRNA)',exact=True).click()
    check('Keyboard-accessible ordering changes the column order',selected()==['title','mirna','disease','cell_line'])
    click(page.locator('#templates-panel > summary'),'templates-open')
    page.locator('#template-name').fill('QA — микроРНК и клетки')
    click(page.locator('#template-save'),'template-save')
    check('Template is saved', 'QA — микроРНК и клетки' in page.locator('#template-list').inner_text())
    template_path=download(page.locator('#template-download'),'table-template.json')
    check('Portable template has the selected order',json.loads(template_path.read_text())['columns']==selected())
    click(page.locator('#apply-columns'),'apply-columns')
    check('Apply opens the result table',page.get_by_role('tab',name='Результаты',exact=True).get_attribute('aria-selected')=='true')
    page.reload(wait_until='domcontentloaded');tab('Настроить таблицу')
    expect(page.locator('#selected-column-list .selected-row')).to_have_count(4)
    check('Applied columns survive a reload',selected()==['title','mirna','disease','cell_line'])
    click(page.locator('#collapse-columns'),'collapse-groups')
    check('All groups can be collapsed',page.locator('.column-group[open]').count()==0)
    page.locator('#column-search').fill('клеточная линия')
    expect(page.locator('.column-option:visible')).to_have_count(1)
    check('Searching reveals matching fields inside collapsed groups',page.locator('[data-column="cell_line"]').is_visible())
    page.locator('#column-search').fill('')
    click(page.locator('#expand-columns'),'expand-groups')
    check('All groups can be expanded',page.locator('.column-group[open]').count()==9)
    click(page.locator('[data-preset="rna"]'),'rna-preset-second')
    page.locator('#template-import').set_input_files(str(template_path))
    expect(page.locator('#selected-column-list .selected-row')).to_have_count(4)
    check('Portable template can be imported',selected()==['title','mirna','disease','cell_line'])
    tab('Архив')
    shot('archive-before')
    page.locator('#import_archive').set_input_files(str(Path(args.archive).resolve()))
    expect(page.locator('#run_status')).to_contain_text('Архив открыт: 30')
    shot('archive-after')
    tab('Результаты');expect(page.locator('#results .dataTables_info')).to_contain_text('30')
    check('Archived column preferences are restored',selected()==['title','year','disease','cell_line','mirna','assay_method'])
    check('Titles link even with DOI and URL columns hidden',page.locator('#results tbody .article-title-link').first.get_attribute('href').startswith('https://pubmed.ncbi.nlm.nih.gov/'))
    search=page.locator('#results .dataTables_filter input')
    shot('filter-before');search.fill('MCF-7');expect(page.locator('#results .dataTables_info')).to_contain_text('15');shot('filter-after')
    page.locator('#results .dataTables_scrollHead th').filter(has_text='Год публикации').first.click()
    page.locator('#results .dataTables_scrollHead th').filter(has_text='Год публикации').first.click()
    page.wait_for_timeout(500)
    csv_path=download(page.locator('#download_csv'),'filtered.csv')
    names,rows=rows_csv(csv_path)
    check('CSV contains exactly the visible filtered rows',len(rows)==15 and all('MCF-7' in row['cell_line'] for row in rows))
    check('CSV follows the selected columns',names==['title','year','disease','cell_line','mirna','assay_method'])
    years=[int(row['year']) for row in rows]
    check('CSV follows table sorting',years==sorted(years,reverse=True))
    download(page.locator('#download_xlsx'),'filtered.xlsx')
    page.locator('#export_filtered').uncheck()
    _,all_rows=rows_csv(download(page.locator('#download_csv'),'all-rows.csv'))
    check('Exporting all rows can be selected explicitly',len(all_rows)==30)
    page.locator('#export_filtered').check()
    search.fill('NO_MATCHING_RESEARCH_XYZ');expect(page.locator('#results .dataTables_info')).to_contain_text('Нет строк')
    empty_names,empty=rows_csv(download(page.locator('#download_csv'),'empty.csv'))
    check('Zero matches export headers without unrelated records',not empty and empty_names==names)
    click(page.locator('#clear-table-filters'),'reset-table-filters')
    expect(page.locator('#results tbody .article-title-link')).to_have_count(25)
    expect(search).to_have_value('')
    click(page.locator('#toggle-column-filters'),'show-column-filters')
    check('Column filters expand',page.locator('#results .dataTables_scrollHead thead tr').nth(1).is_visible())
    click(page.locator('#toggle-column-filters'),'hide-column-filters')
    check('Column filters collapse',not page.locator('#results .dataTables_scrollHead thead tr').nth(1).is_visible())
    click(page.locator('#toggle-table-density'),'compact-rows')
    check('Compact table mode is active',page.locator('body').evaluate('(el)=>el.classList.contains("compact-table")'))
    click(page.locator('#expand-table'),'fullscreen-table')
    check('Expanded table fills the window',page.locator('#results-surface').bounding_box()['width']>=1400)
    shot('desktop-table')
    page.keyboard.press('Escape')
    check('Escape leaves expanded mode',not page.locator('body').evaluate('(el)=>el.classList.contains("table-expanded")'))
    tab('Проверка')
    page.locator('#review_field + .selectize-control input').fill('Клеточная линия')
    page.locator('.selectize-dropdown [data-value="cell_line"]').click()
    expect(page.locator('#review_value')).to_have_value('MCF-7')
    page.locator('#review_value').fill('QA reviewed cell line')
    page.locator('#review_basis').fill('Synthetic fixture, browser persistence test.')
    click(page.locator('#save_review'),'review-save')
    expect(page.locator('#review_evidence')).to_contain_text('Synthetic fixture')
    tab('Архив');click(page.locator('#reprocess_archive'),'reprocess')
    tab('Проверка');expect(page.locator('#review_value')).to_have_value('QA reviewed cell line')
    check('New field review survives offline reprocessing',True)
    tab('Архив');download(page.locator('#download_archive'),'reviewed-archive.json')
    tab('Настроить таблицу');click(page.locator('[data-preset="rna"]'),'final-rna-preset')
    click(page.locator('#collapse-columns'),'final-collapse')
    for i in [1,2,3,4]: page.locator('.column-group[data-group="'+str(i)+'"] > summary').click()
    if page.locator('#search-panel').get_attribute('open') is not None: page.locator('#search-panel > summary').click()
    expect(page.locator('#column_preview th')).to_have_count(len(selected()))
    expect(page.locator('.shiny-notification')).to_have_count(0, timeout=15000)
    page.locator('#column-groups').evaluate('(el)=>el.scrollTop=0')
    page.locator('#selected-column-list').evaluate('(el)=>el.scrollTop=0')
    page.evaluate('window.scrollTo(0,0)');shot('desktop')
    check('Desktop document has no horizontal overflow',page.evaluate('document.documentElement.scrollWidth <= innerWidth'))
    page.set_viewport_size({'width':390,'height':844});page.evaluate('window.scrollTo(0,0)');shot('mobile')
    check('Mobile document has no horizontal overflow',page.evaluate('document.documentElement.scrollWidth <= innerWidth'))
    check('Mobile checkboxes remain usable',page.locator('.column-option:visible').first.bounding_box()['height']>=40)
    tab('Результаты');page.locator('#expand-table').click();shot('mobile-table');page.keyboard.press('Escape')
    check('No JavaScript errors',not errors)
    (out/'browser-results.json').write_text(json.dumps({'url':args.url,'passed':len(checks),'checks':checks,'javascript_errors':errors},ensure_ascii=False,indent=2))
    browser.close()
print('BROWSER',len(checks),'checks passed')
