# Behavioral acceptance tests for failures found during the original-task audit.
neg <- extract_detail_fields('No deviation from Hardy-Weinberg equilibrium was observed.')
check_equal('HWE negation is preserved', neg$hwe, 'отклонений не обнаружено')
check_equal('A non-randomized clinical trial is not RCT', metadata_publication_type('Clinical Trial'), 'клиническое испытание (рандомизация не подтверждена)')
check_equal('Nonrandomized metadata is not RCT', metadata_publication_type('Nonrandomized Controlled Trial'), 'нерандомизированное исследование')
check_equal('Explicit randomized metadata remains RCT', metadata_publication_type('Journal Article; Randomized Controlled Trial'), 'RCT')
check_equal('Inequality is preserved in an extracted p-value', p_expressions('ACTN3 rs1815739: p < 0.05'), 'p < 0.05')
check_equal('Unicode p-value and scientific notation survive', p_expressions('p ≤ 1.00 × 10−5'), 'p ≤ 1.00 × 10−5')
check_equal('Impossible p-values are rejected', p_expressions('p = 7.2'), character())

missing_doi <- rbind(make_article('A'), make_article('B'))
foreign_text <- data.frame(doi = '', source_id = 'B', fulltext = 'A total of 777 athletes were enrolled.')
safe_join <- enrich_final_table(missing_doi, open_fulltext_df = foreign_text)
check_equal('Empty DOI never attaches another article full text', safe_join$sample_size[safe_join$source_id == 'A'], '')
check_equal('Source ID still attaches the correct full text', safe_join$sample_size[safe_join$source_id == 'B'], '777')
check_equal('Abstract-only rows have a qualitative review status', safe_join$extraction_confidence[1], 'требует проверки')

same <- rbind(make_article('A', pmid='123', title='Same publication', doi='10.1234/same'), make_article('B', pmid='123', title='Same publication'))
same$source <- c('PubMed', 'OpenAlex')
check_equal('PMID deduplicates a record whose DOI is missing', nrow(deduplicate_articles(same)), 1L)
same$doi[2] <- '10.1234/different'
check_equal('Conflicting DOI values are never collapsed by title or PMID', nrow(deduplicate_articles(same)), 2L)

full_only <- make_article('F', pmid='99', title='Sports genetics study')
full_only <- build_final_table(full_only, sd_empty_df(), openalex_empty_df(), settings)
full_only <- enrich_final_table(full_only, data.frame(pmid='99', fulltext='[[SECTION: Results]]\nACTN3 rs1815739 genotype was associated with strength (p < 0.01).'))
check_equal('SNPs in full text are included', full_only$snp, 'rs1815739')
check_equal('Genes in full text are included', full_only$gene, 'ACTN3')
check_equal('Full text source is recorded', full_only$text_source, 'pmc')
refs <- '[[SECTION: Introduction]]\nACTN3 rs99999 was found in a prior study.\n[[SECTION: Methods]]\nA total of 100 athletes were enrolled.\n[[SECTION: Results]]\nACTN3 rs1815739 genotype was associated with strength (p = 0.01).\n[[SECTION: References]]\nACE rs777 in athletes (p = 0.003).'
a <- extract_associations(refs, 'test', hgnc_symbols)
check_equal('Association extraction excludes background and bibliography', a$snp, 'rs1815739')
check_equal('SNP-specific p-value is preserved', a$p_value, 'p = 0.01')

linked <- extract_associations('[[SECTION: Results]]\nACTN3 rs1815739 R allele was associated with strength: beta = -0.4, 95% CI -0.6 to -0.2, p < 0.01.\nACE rs4343 A allele was associated with endurance: odds ratio = 1.8, 95% CI 1.1–2.5, p = 0.02.', 'test', hgnc_symbols)
check_equal('Separate SNP results produce separate associations', nrow(linked), 2L)
check_equal('Negative effect is preserved', linked$effect_value[1], '-0.4')
check('Negative CI bounds are preserved', grepl('-0.6 to -0.2', linked$ci[1], fixed=TRUE))
check_equal('Second SNP receives its own p-value', linked$p_value[2], 'p = 0.02')
check('Effect allele retains its identity', grepl('R allele', linked$allele[1], fixed=TRUE))
ambiguous <- extract_associations('ACTN3 rs1815739 and ACE rs4343 had p = 0.01 and p = 0.3.', 'test', hgnc_symbols)
check('Multiple SNPs are marked ambiguous', grepl('неоднозначно', ambiguous$status))
check_equal('Ambiguous comparisons do not get arbitrary numbers', ambiguous$p_value, '')
adjusted <- extract_associations('ACTN3 rs1815739 R allele was associated with strength: p = 0.002, adjusted p = 0.04 after Bonferroni correction.', 'test', hgnc_symbols)
check_equal('Adjusted p-value belongs to the same SNP', adjusted$p_adjusted, 'p = 0.04')

facts <- extract_detail_fields('[[SECTION: Methods]]\nParticipants were recruited between 2018 and 2020. A total of 150 athletes were enrolled: 80 male swimmers and 70 female sprinters. Models were adjusted for age, sex and BMI.\n[[SECTION: Results]]\nThe ACTN3 rs1815739 R allele was associated with higher strength (p < 0.01).\n[[SECTION: Data availability]]\nData are available at https://zenodo.org/records/12345.')
check('Study period is extracted independently from publication date', grepl('2018 and 2020', facts$study_period, fixed=TRUE))
check('Group sizes retain their labels', grepl('80 male swimmers and 70 female sprinters', facts$sample_groups, fixed=TRUE))
check('Actual sport replaces a placeholder', grepl('swimmers', facts$sport, fixed=TRUE))
check('Actual model covariates are retained', grepl('age, sex and BMI', facts$covariates, fixed=TRUE))
check('Repository URL is available separately', identical(facts$data_links, 'https://zenodo.org/records/12345'))
check('Absence of adjustment does not invent significance', !nzchar(extract_detail_fields('Multiple comparisons were discussed.')$p_adj))
check('Mentioning BMI alone does not make it a model covariate', !nzchar(extract_detail_fields('BMI was measured in athletes.')$covariates))
check('A generic data statement does not invent a repository', !grepl('Dryad|Zenodo', extract_detail_fields('Data availability: data are not available.')$data_avail))

xml <- '<article><body><sec><title>Methods</title><sec><title>Participants</title><p>A total of 20 athletes were enrolled.</p></sec></sec><sec><title>Results</title><table-wrap><label>Table 1</label><table><thead><tr><th>SNP</th><th>Phenotype</th><th>OR</th><th>p</th></tr></thead><tbody><tr><td>rs4343</td><td>endurance</td><td>1.8</td><td>0.02</td></tr></tbody></table></table-wrap></sec></body><back><ref-list><ref><p>rs9999 p = 0.0001</p></ref></ref-list><sec><title>Data availability</title><p>https://zenodo.org/records/12345</p></sec></back></article>'
parsed <- strip_xml(xml)
check('Nested methods section retains its parent', grepl('Methods / Participants', parsed, fixed=TRUE))
check('PMC table binds headers to cells', grepl('SNP: rs4343 | Phenotype: endurance | OR: 1.8 | p: 0.02', parsed, fixed=TRUE))
check('PMC back-matter data links are retained', grepl('https://zenodo.org/records/12345', parsed, fixed=TRUE))
check('PMC reference SNP is excluded', !grepl('rs9999', parsed, fixed=TRUE))
check('HTML preserves table rows', grepl('TABLE_ROW', html_body_text('<html><body><table><tr><th>SNP</th><th>OR</th></tr><tr><td>rs4343</td><td>1.8</td></tr></table></body></html>'), fixed=TRUE))

full_only <- assess_evidence(full_only)
check('Evidence assessment never awards A/B/C/D from study design', !full_only$evidence_profile %in% c('A','B','C','D'))
check('Evidence profile distinguishes replication from paper count', grepl('Независимость', full_only$evidence_reasons, fixed=TRUE))
archive_file <- tempfile(fileext='.json')
write_research_archive(full_only, archive_file)
restored <- read_research_archive(archive_file)
check_equal('Archive roundtrip preserves article values', restored$results, full_only$results)
check_equal('Archive roundtrip preserves full text', attr(restored,'documents'), attr(full_only,'documents'))
check_equal('Archive roundtrip preserves associations', attr(restored,'associations')$p_value, attr(full_only,'associations')$p_value)
reviewed <- review_article_field(restored, restored$article_id[1], 'sample_size', '246', 'Synthetic reviewer statement for persistence test.')
check_equal('Manual review updates the selected field', reviewed$sample_size, '246')
check('Manual review retains the previous value', identical(attr(reviewed,'review_log')[[1]]$before, restored$sample_size))
write_research_archive(reviewed, archive_file)
restored_review <- read_research_archive(archive_file)
check_equal('Verified fields survive offline reprocessing', reprocess_archive(restored_review)$sample_size, '246')
check_error('Review requires an explicit basis', review_article_field(restored, restored$article_id[1], 'age','30',''), 'основание')
check_error('Identifiers cannot be edited through field review', review_article_field(restored, restored$article_id[1], 'doi','fake','test'), 'нельзя')
empty <- enrich_final_table(build_final_table(pubmed_empty_df(), sd_empty_df(), openalex_empty_df(), settings))
check_equal('Empty search can be enriched without errors', nrow(empty), 0L)
write_research_archive(empty, archive_file)
check_equal('Empty archive is readable', nrow(read_research_archive(archive_file)), 0L)
unlink(archive_file)

check_equal('Clinical protocol is not a completed trial', metadata_publication_type('Clinical Trial Protocol'), 'протокол клинического испытания')
check_equal('ACE adverse childhood experience acronym is not a gene', extract_gene('Adverse childhood experiences (ACE) were associated with athletic activity.', hgnc_symbols), '')
check_equal('ACTN-3 spelling is normalized', extract_gene('ACTN-3 gene polymorphism in athletes.', hgnc_symbols), 'ACTN3')
check_equal('Russian HWE negative statement stays negative', extract_detail_fields('Отклонений от равновесия Харди-Вайнберга не обнаружено.')$hwe, 'отклонений не обнаружено')
check('Russian sports and sample groups are retained', nzchar(extract_detail_fields('Обследовано 120 спортсменов: 80 мужчин и 40 женщин, занимающихся футболом.')$sample_groups))
context <- extract_associations('[[SECTION: Results]]\nThe C allele was associated with strength (p < 0.05).', 'context', hgnc_symbols, 'ACTN3 rs1815739 genotype in athletes')
check_equal('Title-only SNP link is explicitly provisional', context$link_method, 'single_snp_title_requires_review')
check('Title-only SNP link retains supporting title', grepl('rs1815739', context$link_evidence, fixed=TRUE))
no_context <- extract_associations('[[SECTION: Results]]\nThe ACE A allele was associated with strength (p = 0.02).', 'context', hgnc_symbols, 'ACTN3 rs1815739 genotype in athletes')
check_equal('Conflicting gene prevents title-based attribution', nrow(no_context), 0L)
age_adjust <- extract_associations('ACTN3 rs1815739 R allele was associated with strength in models adjusted for age (p = 0.03).', 'test', hgnc_symbols)
check_equal('Covariate adjustment is not multiple-testing correction', age_adjust$p_adjusted, '')
check_equal('Covariate-adjusted regression p is preserved', age_adjust$p_value, 'p = 0.03')
check_equal('Bibliographic URLs are not data repository URLs', extract_detail_fields('Data availability https://zenodo.org/records/12345 and https://pubmed.ncbi.nlm.nih.gov/123/.')$data_links, 'https://zenodo.org/records/12345')
merged_xml <- '<table><tr><th>SNP</th><th>OR</th></tr><tr><td rowspan="2">rs4343</td><td>1.8</td></tr><tr><td>1.2</td></tr></table>'
check('Merged tables retain ambiguous row rather than inferred headers', all(grepl('AMBIGUOUS_TABLE', xml_table_lines(xml2::read_xml(merged_xml))[-1], fixed=TRUE)))
pdf <- pdf_document_text(c('Results\nACTN3 rs1815739 strength p < 0.01\nReferences\nACE rs777 p = 0.02', 'ACE rs888 p = 0.03'))
check_equal('PDF bibliography is excluded across page boundaries', extract_associations(pdf, 'pdf', hgnc_symbols)$snp, 'rs1815739')
no_pmid <- full_only
no_pmid$pmid <- ''
no_pmid$fulltext_url <- 'https://pmc.ncbi.nlm.nih.gov/articles/PMC123/'
with_pmc <- enrich_final_table(no_pmid, data.frame(pmid='', fulltext_url=no_pmid$fulltext_url, fulltext='[[SECTION: Methods]]\nA total of 555 athletes were enrolled.'))
check_equal('PMC URL can join full text without a PMID', with_pmc$sample_size, '555')
manual_gene <- review_article_field(restored, restored$article_id[1], 'gene', 'ACE', 'Reviewer-confirmed gene for persistence fixture')
manual_gene <- reprocess_archive(reprocess_archive(manual_gene))
check_equal('Manual gene survives repeated offline extraction', manual_gene$gene, 'ACE')
check_equal('Manual gene evidence survives repeated extraction', jsonlite::fromJSON(manual_gene$extraction_evidence)$gene$status, 'проверено пользователем')
recent <- extract_detail_fields('Between 2017 and 2025, 122 male professional football players were enroled.')
check_equal('Recruitment count with modifiers and British spelling', recent$sample_size, '122')
check('Recruitment period survives British spelling', grepl('2017 and 2025', recent$study_period, fixed=TRUE))
manifest <- jsonlite::read_json(file.path(ROOT, 'manifest.json'))
check('Deployment manifest includes all runtime R modules', all(paste0('src/', list.files(file.path(ROOT,'src'), pattern='[.]R$')) %in% names(manifest$files)))
check_equal('Significance threshold is not an observed SNP association', nrow(extract_associations('For ACTN3 rs1815739, the significance threshold was p < 0.05.', 'threshold', hgnc_symbols)), 0L)
check_equal('HWE quality-control p is not a phenotype association', nrow(extract_associations('ACTN3 rs1815739 was in Hardy-Weinberg equilibrium (p = 0.3).', 'hwe', hgnc_symbols)), 0L)
check_equal('PDF bibliography is excluded from the article SNP list', extract_snp(section_subset(pdf, c('method','result','page'))), 'rs1815739')
check_equal('Section fallback never mines PDF references', section_subset('[[SECTION: Page 1 / References]]\nACTN3 rs777 genotype.', 'methods'), '')
