# Full-width research workspace and native, keyboard-accessible disclosure groups.
disclosure <- function(title, ..., open = FALSE, id = NULL, class = "filter-group") {
  tags$details(id = id, class = class, open = if (open) NA else NULL,
    tags$summary(title), div(class = "disclosure-body", ...))
}

column_builder_ui <- function() {
  config <- list(labels = as.list(TABLE_COLUMN_LABELS), groups = TABLE_COLUMN_GROUPS,
    presets = TABLE_COLUMN_PRESETS, initial = TABLE_COLUMN_PRESETS$core)
  div(id = "column-builder",
    tags$script(id = "column-config", type = "application/json", HTML(jsonlite::toJSON(config, auto_unbox = FALSE))),
    div(class = "section-heading",
      div(h2("Настроить таблицу"), p("Выберите поля для таблицы и выгрузки CSV / XLSX.")),
      disclosure("Мои шаблоны",
        tags$label(`for` = "template-name", "Название шаблона"),
        tags$input(id = "template-name", type = "text", maxlength = "64", placeholder = "Например, микроРНК и опухоли", class = "form-control"),
        tags$button(id = "template-save", type = "button", class = "btn btn-default", "Сохранить шаблон"),
        tags$label(`for` = "template-list", "Сохранено в этом браузере"),
        tags$select(id = "template-list", class = "form-control", tags$option(value = "", "Выберите шаблон")),
        div(class = "button-row",
          tags$button(id = "template-load", type = "button", class = "btn btn-default", "Открыть"),
          tags$button(id = "template-delete", type = "button", class = "btn btn-default", "Удалить"),
          tags$button(id = "template-download", type = "button", class = "btn btn-default", "Скачать JSON")),
        tags$label(`for` = "template-import", "Импорт шаблона JSON"),
        tags$input(id = "template-import", type = "file", accept = ".json,application/json"),
        p(class = "field-help", "Шаблон содержит только названия и порядок колонок."),
        id = "templates-panel", class = "template-panel")),
    div(class = "preset-row", span(class = "control-label", "Готовые наборы"),
      tags$button(type = "button", class = "btn preset-button", `data-preset` = "core", "Основные"),
      tags$button(type = "button", class = "btn preset-button", `data-preset` = "genetics", "Генетика"),
      tags$button(type = "button", class = "btn preset-button", `data-preset` = "diseases", "Заболевания"),
      tags$button(type = "button", class = "btn preset-button", `data-preset` = "cells", "Клеточные исследования"),
      tags$button(type = "button", class = "btn preset-button", `data-preset` = "rna", "МикроРНК")),
    div(class = "builder-grid",
      div(class = "available-columns",
        div(class = "builder-heading", h3("Доступные колонки"),
          tags$button(id = "collapse-columns", type = "button", class = "text-button", "Свернуть всё"),
          tags$button(id = "expand-columns", type = "button", class = "text-button", "Развернуть всё")),
        div(class = "column-search-row",
          tags$input(id = "column-search", type = "search", class = "form-control", placeholder = "Найти колонку…", `aria-label` = "Найти колонку"),
          tags$button(id = "select-all-columns", type = "button", class = "text-button", "Выбрать все"),
          tags$button(id = "clear-columns", type = "button", class = "text-button", "Снять выделение")),
        div(id = "column-groups", lapply(seq_along(TABLE_COLUMN_GROUPS), function(i) {
          fields <- TABLE_COLUMN_GROUPS[[i]]
          tags$details(class = "column-group", `data-group` = i, open = if (i <= 4L) NA else NULL,
            tags$summary(span(names(TABLE_COLUMN_GROUPS)[i]), span(class = "group-count")),
            div(class = "group-tools", tags$label(class = "checkbox-label",
              tags$input(type = "checkbox", `data-group-toggle` = i), "Выбрать группу")),
            div(class = "column-options", lapply(fields, function(field) tags$label(class = "checkbox-label column-option",
              `data-field` = field, tags$input(type = "checkbox", `data-column` = field,
                checked = if (field %in% TABLE_COLUMN_PRESETS$core) NA else NULL),
              span(unname(TABLE_COLUMN_LABELS[[field]]))))))
        })),
        p(id = "column-search-empty", hidden = NA, "Колонки не найдены. Попробуйте другое название.")),
      div(class = "selected-columns",
        h3(id = "selected-count", "Выбрано 13 колонок"),
        p(class = "field-help", "Перетащите строки или используйте кнопки вверх и вниз."),
        tags$ol(id = "selected-column-list", `aria-label` = "Порядок колонок"),
        p(id = "empty-selection", hidden = NA, "Выберите хотя бы одну колонку."),
        p(class = "field-help selected-help", "Одна строка — статья. Несколько результатов сохраняются с исходными фрагментами."))),
    div(class = "preview-panel", div(class = "builder-heading", h3("Предпросмотр таблицы"), uiOutput("preview_note")),
      div(class = "preview-scroll", uiOutput("column_preview"))),
    div(class = "builder-footer",
      div(tags$p(id = "column-draft-status", role = "status", `aria-live` = "polite"), uiOutput("column_summary")),
      div(class = "button-row",
        tags$button(id = "reset-column-draft", type = "button", class = "btn btn-default", "Отменить изменения"),
        tags$button(id = "apply-columns", type = "button", class = "btn btn-primary", "Применить к таблице"))))
}

search_controls_ui <- function(queries) {
  disclosure("Поиск и фильтры",
    div(class = "search-grid",
      disclosure("Тема и источники",
        selectInput("research_profile", "Тема исследования", choices = setNames(names(RESEARCH_PROFILES), vapply(RESEARCH_PROFILES, `[[`, character(1), "label")), selected = "sports", width = "100%"),
        p(class = "field-help", "Тема подставляет пример запроса и набор колонок. Уточните запрос под свою задачу."),
        checkboxGroupInput("sources", "Источники", choices = c("PubMed" = "pubmed", "Elsevier" = "sciencedirect", "OpenAlex" = "openalex"), selected = c("pubmed", "sciencedirect", "openalex"), inline = TRUE),
        selectInput("openalex_scope", "Охват OpenAlex", choices = c("Российские и русскоязычные" = "russian", "Все страны и языки" = "global"), selected = "russian", width = "100%"),
        conditionalPanel("input.research_profile === 'sports'", checkboxInput("topic_filter", "Строгий фильтр: генетика и спорт", TRUE)), open = TRUE),
      disclosure("Годы и объём поиска",
        div(class = "year-range", textInput("year_from", "Год с", placeholder = "2020"), textInput("year_to", "Год по", placeholder = "2026")),
        p(class = "field-help", "Границы включаются в поиск. Можно заполнить только одну или оставить обе пустыми."),
        numericInput("max_records", "Статей на каждый источник", 200, min = 0, step = 1, width = "100%"),
        p(class = "field-help", "0 — максимум, разрешённый источником."),
        checkboxInput("fulltext", "Получать доступные полные тексты", TRUE),
        p(class = "field-help", "Полные тексты улучшают извлечение и увеличивают время поиска."), open = TRUE),
      disclosure("Поисковые запросы",
        p(class = "field-help", "Готовые запросы можно менять. AND — «и», OR — «или»."),
        disclosure("PubMed", textAreaInput("query_pubmed", NULL, queries$pubmed, rows = 4, width = "100%"), open = TRUE, class = "query-editor"),
        disclosure("Elsevier", textAreaInput("query_sciencedirect", NULL, queries$sciencedirect, rows = 4, width = "100%"), class = "query-editor"),
        disclosure("OpenAlex", textAreaInput("query_openalex", NULL, queries$openalex, rows = 4, width = "100%"), class = "query-editor"),
        actionButton("reset_queries", "Вернуть запросы темы", class = "btn-default"), open = TRUE)),
    disclosure("Ключ Elsevier и доступ",
      passwordInput("elsevier_key", "Свой ключ Elsevier", value = "", placeholder = "Серверный ключ или ключ текущего сеанса", width = "100%"),
      p(class = "field-help", "Введённый ключ действует только в сеансе. Если ScienceDirect недоступен, используется Scopus с фильтром Elsevier; способ получения указан в выдаче.")),
    id = "search-panel", class = "search-panel", open = TRUE)
}

research_ui <- function(queries) {
  page_navbar(title = div("SportGen Parser", span(class = "version-label", "2.0")),
    theme = bs_theme(version = 5, bg = "#f4f1e9", fg = "#102a2d", primary = "#d95d39"),
    header = tags$head(tags$link(rel = "stylesheet", href = "workspace.css"), tags$script(src = "table-builder.js")),
    nav_panel("Исследования", div(class = "app-shell",
      div(class = "intro", div(h1("Поиск исследований"), p("PubMed, Elsevier и OpenAlex. От запроса к проверяемой таблице.")),
        div(class = "button-row", actionButton("run", "Запустить поиск", class = "btn-primary"),
          downloadButton("download_csv", "CSV"), downloadButton("download_xlsx", "XLSX"))),
      search_controls_ui(queries), uiOutput("run_status"),
      navset_tab(id = "workspace_tab",
        nav_panel("Результаты", value = "results",
          div(id = "results-surface", class = "results-surface",
            div(class = "results-toolbar", uiOutput("metrics"), div(class = "button-row",
              tags$button(id = "toggle-column-filters", type = "button", class = "btn btn-default", `aria-pressed` = "false", "Фильтры по колонкам"),
              tags$button(id = "clear-table-filters", type = "button", class = "btn btn-default", "Сбросить фильтры"),
              tags$button(id = "toggle-table-density", type = "button", class = "btn btn-default", `aria-pressed` = "false", "Компактные строки"),
              tags$button(id = "expand-table", type = "button", class = "btn btn-default", `aria-pressed` = "false", "На весь экран"))),
            p(class = "result-help", "Нажмите на название статьи, PMID или DOI, чтобы открыть оригинал. Нажмите заголовок колонки для сортировки."),
            DTOutput("results"),
            div(class = "export-note", checkboxInput("export_filtered", "CSV / XLSX: учитывать фильтры и сортировку таблицы", TRUE), uiOutput("export_summary")))),
        nav_panel("Настроить таблицу", value = "columns", column_builder_ui()),
        nav_panel("Ассоциации", value = "associations", p(class = "result-help", "Связи SNP со статистикой. Для микроРНК и клеток используйте поля таблицы и исходные фрагменты во вкладке «Проверка». Неоднозначные сравнения требуют проверки."), downloadButton("download_associations", "Ассоциации CSV"), DTOutput("associations")),
        nav_panel("Проверка", value = "review",
          p(class = "result-help", "Сверьте значение с сохранённым текстом или оригиналом. Подтверждение хранится вместе с основанием."),
          selectInput("review_article", "Статья", choices = character(), width = "100%"),
          selectInput("review_field", "Поле", choices = setNames(REVIEWABLE_COLS, unname(TABLE_COLUMN_LABELS[REVIEWABLE_COLS])), width = "100%"),
          div(class = "review-grid", textAreaInput("review_value", "Значение", rows = 4, width = "100%"), textAreaInput("review_basis", "Основание: цитата, раздел / страница или пояснение", rows = 4, width = "100%")),
          div(class = "button-row", actionButton("save_review", "Подтвердить поле", class = "btn-primary"), actionButton("undo_review", "Отменить последнюю проверку")),
          disclosure("Основание текущего значения", verbatimTextOutput("review_evidence"), open = TRUE),
          disclosure("Сохранённый текст статьи", verbatimTextOutput("review_document"))),
        nav_panel("Доказательства", value = "evidence", p(class = "result-help", "Предварительный профиль, требующий экспертной оценки. Это не GRADE и не рейтинг OpenEvidence. Сводка ассоциаций относится к SNP; число публикаций не означает независимое воспроизведение."), DTOutput("evidence_profiles"), h3("Публикации по сопоставляемым признакам"), DTOutput("evidence_summary")),
        nav_panel("Архив", value = "archive", h2("Продолжить исследование позже"),
          p("Архив сохраняет статьи, доступные тексты, ассоциации, проверенные поля и выбранные колонки. Скачайте его до нового поиска или закрытия страницы."),
          downloadButton("download_archive", "Скачать архив JSON"),
          fileInput("import_archive", "Открыть сохранённый архив", accept = ".json"),
          actionButton("reprocess_archive", "Повторить извлечение из архива"),
          p(class = "field-help", "Повторное извлечение выполняется без сети и сохраняет подтверждённые поля. Ключи в архив не входят.")),
        nav_panel("Журнал", value = "log", verbatimTextOutput("log", placeholder = TRUE)),
        nav_panel("О проекте", value = "about",
          h2("Проверяемые данные из публикаций"),
          p("Поля заполняются по правилам из метаданных, аннотаций и доступных полных текстов. Исходные формулировки сохраняются; извлечение требует проверки исследователем."),
          tags$ul(tags$li("Словари заболеваний, клеточных линий и РНК не исчерпывающие. Неизвестные обозначения можно внести вручную."),
            tags$li("OpenAlex не равен eLIBRARY по охвату. Прямой поиск eLIBRARY не подключён."),
            tags$li("Закрытые тексты не обходятся. Сканы PDF не распознаются; сложные таблицы требуют ручной проверки."),
            tags$li("Crossref дополняет DOI и библиографию. Он не является отдельным поисковым источником.")))))))
}
